name: Release Docker Image

on:
    workflow_dispatch:
    push:
        tags:
            - "v*"

jobs:
    docker:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Determine version
              id: version
              run: |
                  if [ -n "${GITHUB_REF#refs/tags/}" ]; then
                    VERSION=${GITHUB_REF#refs/tags/}
                  else
                    VERSION=$(curl -s https://api.github.com/repos/NLion74/ics-webuntis/releases/latest | jq -r .tag_name)
                  fi
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: nlion/ics-webuntis:${{ env.VERSION }},nlion/ics-webuntis:latest
                  cache-from: type=registry,ref=nlion/ics-webuntis:latest
                  cache-to: type=inline
